"""empty message

Revision ID: 03a40a16e97c
Revises: 
Create Date: 2021-04-16 13:37:01.116630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a40a16e97c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('euser',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=20), nullable=True),
    sa.Column('u_type', sa.String(length=5), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('item_tag', sa.String(length=20), nullable=True),
    sa.Column('item_price', sa.Float(precision=2), nullable=True),
    sa.Column('item_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_list',
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_num', 'item_id')
    )
    op.create_table('cust_order',
    sa.Column('order_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(precision=2), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('checkout', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['euser.uid'], ),
    sa.PrimaryKeyConstraint('order_num')
    )
    op.create_table('customer',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('phone_num', sa.String(length=14), nullable=True),
    sa.Column('street_num', sa.String(length=5), nullable=True),
    sa.Column('street_name', sa.String(length=20), nullable=True),
    sa.Column('town', sa.String(length=40), nullable=True),
    sa.Column('parish', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rewards_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['euser.uid'], ),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('cust_order')
    op.drop_table('item_list')
    op.drop_table('item')
    op.drop_table('euser')
    # ### end Alembic commands ###
