"""empty message

Revision ID: 077069970846
Revises: 09b92e2242b4
Create Date: 2021-03-26 00:32:15.623671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '077069970846'
down_revision = '09b92e2242b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cust_order',
    sa.Column('order_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(precision=2), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('checkout', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['euser.uid'], ),
    sa.PrimaryKeyConstraint('order_num')
    )
    op.drop_table('order')
    op.drop_constraint('item__list_order_num_fkey', 'item__list', type_='foreignkey')
    op.create_foreign_key(None, 'item__list', 'cust_order', ['order_num'], ['order_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item__list', type_='foreignkey')
    op.create_foreign_key('item__list_order_num_fkey', 'item__list', 'order', ['order_num'], ['order_num'])
    op.create_table('order',
    sa.Column('order_num', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('checkout', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['euser.uid'], name='order_uid_fkey'),
    sa.PrimaryKeyConstraint('order_num', name='order_pkey')
    )
    op.drop_table('cust_order')
    # ### end Alembic commands ###
