"""empty message

Revision ID: 09b92e2242b4
Revises: 4805fb71d31e
Create Date: 2021-03-19 16:28:22.528997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b92e2242b4'
down_revision = '4805fb71d31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'item_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('item_list', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
