"""empty message

Revision ID: 4805fb71d31e
Revises: b9bd5fbc3cab
Create Date: 2021-03-19 16:25:32.695694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4805fb71d31e'
down_revision = 'b9bd5fbc3cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item__list',
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
    sa.ForeignKeyConstraint(['order_num'], ['order.order_num'], ),
    sa.PrimaryKeyConstraint('order_num', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item__list')
    # ### end Alembic commands ###
