"""empty message

Revision ID: d2620c9333f3
Revises: 73e40c35cc9b
Create Date: 2021-03-29 23:02:40.657033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2620c9333f3'
down_revision = '73e40c35cc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_list_order_num_fkey', 'item_list', type_='foreignkey')
    op.drop_constraint('item_list_item_id_fkey', 'item_list', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('item_list_item_id_fkey', 'item_list', 'item', ['item_id'], ['item_id'])
    op.create_foreign_key('item_list_order_num_fkey', 'item_list', 'cust_order', ['order_num'], ['order_num'])
    # ### end Alembic commands ###
